language: node_js
node_js:
  - "5.0"

env:
  global:
    # NPM_API_KEY
    - secure: "IEfctrje4QulHyavIMZYnxljU4XvpMnLR8TzCU8ozeQbdoIOq3/WqBl53Mou2Ie65YAbcMNfLmAvXWgNiKR2jE+K9tOyXsIj+Wbrr4b6X1FHqjkTLw8OCcLFD7kO/aptEOzsTZWbpJKao3mtcshHWWiFeeRDANYK6QMSYwoVNLc="

install:
  - bundle install
  - npm install -g npm

script:
  - npm -v
  - ./build && scripts/publish
